### ISSUE TITLE
Preprocess fails with CORS error

### ISSUE THREAD

**Issue by benfoley** [persephone-tools/persephone-frontend#62]
Attempting to preprocess fails, with this error in the console:

```
Access to fetch at 'http://127.0.0.1:8080/v0.1/corpus/preprocess/1' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
 
Using the docker-compose method of running the frontend. Installation etc and loading a few files from the toy Na corpus.

**Comment by aapeliv** [comment]
I'm not able to reproduce this at the moment. This should have been fixed on the web API to add CORS support (see https://github.com/persephone-tools/persephone-web-API/pull/93 and https://github.com/persephone-tools/persephone-web-API/pull/147).

Which commit are you on? Are you able to attach the whole request info here, including HTTP headers?

**Comment by shuttle1987** [comment]
Reopen if CORS is still an issue. Currently the preprocess endpoint is not connected to anything as this will happen on corpus creation.

**Comment by benfoley** [comment]
Thanks, hopefully I’ll have a chance this week to look at it again.

**Comment by shuttle1987** [comment]
Let me know if there's any issues in the recent versions, quite a few things have been fixed since the CORS issue was around.
